### ISSUE TITLE
server response for open

### ISSUE THREAD

**Issue by dmtrlbdv1** [Matthias247/jawampa#40]
Is it possible to get server response for open() method ?

**Comment by dmtrlbdv1** [comment]
I mean how to receive session id ?

**Comment by Matthias247** [comment]
There currently isn't a method. It would be easy to introduce a getter for the sessionId, but I didn't did that because it introduces a race condition in combination with the auto-reconnect feature. When you get a notification delivered that that you got connected this event might already be in the past, so when reacting to it you might already be disconnected or reconnected again and the sessionId you would retrieve with a getter might not match the sessionId that caused the connected event.

It think the most correct way at the moment (without dropping the auto-reconnect functionality) would be to deliver the sessionId with the `statusChanged` observable.

**Comment by dmtrlbdv1** [comment]
statusChanged with sessionId will be very helpful. Right now it is a blocker for us to use this library without knowing sessionId (it is necessary to know this value in our case. I think it is important not only for us)

**Comment by Matthias247** [comment]
Do the changes in cc0b9938fc18c1d338649c0f9b5329c21daf67fa help you?
Changing the status to an interface with various implementations depending on the state is the best I could think of. This means the reason for disconnects could now also be transmitted in the Disconnect events.

This might not be the complete implementation, I have to look at it again on another day.

**Comment by dmtrlbdv1** [comment]
Thank you! Seems like what we need! I hope this feature will be released to maven soon.

**Comment by Matthias247** [comment]
I reworked it a little bit and have realesed it now. Hope it helps you!  
For all others: Sorry for breaking the API. However the necessary adaptions in the connection handlers can be done quite quickly.
