### ISSUE TITLE
MessagePack for sending binary

### ISSUE THREAD

**Issue by dmtrlbdv1** [Matthias247/jawampa#43]
Does jawampa support sending binary  using  MessagePack ? I mean if I have picture data for example and I want to sand it using MessagePack - is it possible? I am asking it because README says "jawampa does not properly support the transmission of binary values as required in the WAMP specification" and now it is not clear all possibilities of sending binaries. Sorry

**Comment by evgzakharov** [comment]
mb you could use base64 for your purpose

**Comment by Matthias247** [comment]
Binary data serialization with Messagepack should work without issues, but I guess it would still be the best if you test and confirm it with the other clients and router of your choice.

The problem with json serialization is that most JSON serializers (including jackson) will serialize binary data simply into a base64 string, but the WAMP specification also requires a 0 character in front of that string (which some environments could also interpret as an empty string). Maybe jackson can also be configured to do that, I haven't studied this in detail.

**Comment by jrogers** [comment]
I'm using binary values with a router supporting only MessagePack and it works fine, Jackson will do the right thing.

The main issue you might run into as Matthias suggested is that if you are using a router with clients using both jackson and msgpack serializations, and your client using MessagePack calls a procedure or publishes an event containing binary data, and the receiving client is using json, the router will convert the binary to base64 automatically for the json client. Your json client would need to handle conversation from base64 to binary itself as the base64 can't be distinguished from a regular json string value, this is why the spec says to prepend the 0 char to allow this more easily. However if you are using Jackson or some other data binding framework, it should be fine since deserialization will likely just try to convert the base64 to say a byte[] value based on the binding type information.

**Comment by rich-jones** [comment]
How do you tell the jawampa client to use MsgPack instead of JSON?
Is there any jawampa documentation beyond what is on its github landing page?
Thank you.

**Comment by Matthias247** [comment]
See the added `WampClientBuilder#withSerializations` parameter from here: https://github.com/Matthias247/jawampa/pull/25/files
