### ISSUE TITLE
Customize object mapper for WampClient

### ISSUE THREAD

**Issue by programmerr47** [Matthias247/jawampa#79]
Hello, I'm using this library in my project for retrieve data by WebSocket. I have Pojos and use Jackson to convert results of rest calls (I also have rest calls) to them. One of the objects came also from WebSocket, and jawampa has it's own objectMapper (default object mapper) to provide converting from json to Pojo. 

The problem is, that I have to setup my objectMapper by introducing CAMEL_CASE_NAMING_STRATEGY and also setting FAIL_ON_UNKNOWN_PROPERTIES to false, to provide not full mapping from json to objects (my objects are far less, than response json from server). So it would be nice If I could configure objectMapper in jawampa.

For example, It would be greate if WampClientBuilder had method objectMapper(ObjectMapper objectMapper) or something like that.

Thank you.

**Comment by the20login** [comment]
I had implemented customizable object mapper, see pull requests.

**Comment by programmerr47** [comment]
@the20login Perfect, thank you. But I'm aware of 9month long silence (I mean last commit in library was made 9month ago). :(

**Comment by the20login** [comment]
Yeah, I'm worried about it too, but it's pull request, ready for merge, so lets hope for the best.

In my case,  I would like to skip empty fields and have a support of Java 8 Datetime. At first, I've tried to extract ObjectMapper via reflection, but it doesn't seems possible (because of private final modifiers).

Of cource, there is always an option to make a fork, but I really don't want to do this.

**Comment by darkl** [comment]
Hi @Matthias247, what about adding another collaborator to the project so he can help with these kind of pull requests?
(I'm not suggesting anyone specific, just suggesting the idea)

Elad

**Comment by Matthias247** [comment]
Hi everyone,
sorry for the delayed response. I have checked and merge the PR.
I can totally understand that the reaction time wasn't good. But unfortunately I currently neither use WAMP professionally nor privately and have to take care of some other projects - so therefore it is not high on my priority list. However I think the suggestion from @darkl is good - but the question is how to find a good maintainer :) Maybe @santhosh-tekuri has interest, since he contributed quite a lot?

**Comment by the20login** [comment]
BTW, what about maven central? Are you plannning to release updated version?

**Comment by programmerr47** [comment]
Hi @Matthias247 Could you please promt to me, when will be released new version

**Comment by Matthias247** [comment]
@the20login @programmerr47 new version should now be on maven central.

**Comment by the20login** [comment]
Awesome, thanks!

**Comment by programmerr47** [comment]
@Matthias247 thank you ;)
@the20login thank you for your contribution
